### ISSUE TITLE
[Feature Request] Respect mirror settings when using auto mesh

### ISSUE THREAD

**Issue by HigasaMitsue** [Inochi2D/inochi-creator#114]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

Currently, the auto mesh ignores the vertex mirror settings.

### Suggested solution

Mirror the auto mesh vertices across the currently enabled mirror axes.

There is an edge case where the user might enable mirror axes on non-symmetrical art, but I think that would fall under user error.

### Additional Context

Low priority, could live without this.

**Comment by seagetch** [comment]
If original image on the texture is completely symmetric, this works well. Otherwise, generated mesh just fit to one side, and does not fit well in another side.
We need to define what is desired when we turn on the mirror setting more precisely.

I resampled the result of contours not to generate too many vertices.
I think that result in asymmetric layout.
Maybe picking up resampled points in one side of mirror, and picking up nearest points from raw contour points for another side is the good way.

**Comment by LunaTheFoxgirl** [comment]
This should be implemented as of this commit by seagetch https://github.com/Inochi2D/inochi-creator/commit/18b8b990518868d23963675dc51d00c06a4c4a77
