### ISSUE TITLE
Image imports from non-ASCII file paths fail on Windows

### ISSUE THREAD

**Issue by 2439905184** [Inochi2D/inochi-creator#28]
=== Args State ===

=== Exception ===
object.Exception@F:\Projects\inochi\inochi2d\source\inochi2d\core\texture.d(84): cannot open file: D:\整理\010收集箱\blender模型\electric-guitar\preview_72814.jpg
----------------
0x00007FF78198AAAD
0x00007FF78198A826
0x00007FF781987680
0x00007FF78196C51A
0x00007FF781887B8E
0x00007FF781881B8B
0x00007FF7818DF7D3
0x00007FF781868267
0x00007FF7818854C2
0x00007FF781885131
0x00007FF78196F205
0x00007FF78196EED7
0x00007FF78196F193
0x00007FF78198BA50
0x00007FF88B877C24 in BaseThreadInitThunk
0x00007FF88C34D721 in RtlUserThreadStart

**Comment by 2439905184** [comment]
will creator support unicode floder name?

**Comment by 2439905184** [comment]
in ascii english floder ,software worked will.

**Comment by LunaTheFoxgirl** [comment]
This is certainly an odd bug, Inochi2D is written in D which stores strings as UTF-8 at all times. I will try to investigate when I can.

Thanks for letting me know

**Comment by LunaTheFoxgirl** [comment]
Tagging @playmer in this since he has the most experience with Windows development

**Comment by louy2** [comment]
Error comes from [inochi2d/core/texture.d#L84]
which originates from `read_image` on L83.

`read_image` comes from the package [imagefmt], at [imagefmt/package.d#L202], and on L210 you can see it uses `fopen` instead of `File.open`. `fopen` does not support Unicode on Windows.

According to [UTF-8 Everywhere], you can work around this by using [`GetShortPathName`]:

> If you use 3rd-party libraries that do not support Unicode, e.g. forwarding file name strings as-is to `fopen()`, you will have to work around with tools such as `GetShortPathName()` as shown above.

[inochi2d/core/texture.d#L84]: https://github.com/Inochi2D/inochi2d/blob/main/source/inochi2d/core/texture.d#L84
[imagefmt]: https://code.dlang.org/packages/imagefmt
[imagefmt/package.d#L202]: https://github.com/tjhann/imagefmt/blob/9c897ef1dcf7c06a9b4f86ca67b597408810298f/imagefmt/package.d#L202
[UTF-8 Everywhere]: http://utf8everywhere.org/
[`GetShortPathName`]: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getshortpathnamew

**Comment by playmer** [comment]
Thanks for doing the digging there. 

I think it'd be better to wrap their `IFImage read_image(Read io, in int c = 0, in int bpc = 8)` overload with some D file stuff in the Read struct instead of trying to carve out a Windows specific path. (This assumes that this path is accessible to us, and that D is utf8 aware in it's file i/o.

It's maybe also worth considering sending them a PR to fix this by doing the same. Not sure why they'd prefer fopen over D's stuff here.

**Comment by LunaTheFoxgirl** [comment]
They use fopen because it needs to be betterC compatible. So I guess we'd need to write a patch that uses the wide character file open.

**Comment by LunaTheFoxgirl** [comment]
This issue should be fixed as of this commit
https://github.com/Inochi2D/inochi2d/commit/8b992eb707b0854048e52b2d22a9ccd0334ba494
